SEP_FingerPrint/Controllers/LecturerController.cs
using SEP_FingerPrint.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Security.Cryptography;
using System.Text;
using System.Linq.Dynamic;
using System.Configuration;
using System.Data.EntityClient;
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.ComponentModel;
using System.Dynamic;
using SEP_FingerPrint.IntegratedModel;
using System.Globalization;
using System.Net.Http;
using Newtonsoft.Json;

namespace SEP_FingerPrint.Controllers
{
    public class LecturerController : Controller
    {

        private Sep2018Entities db = new Sep2018Entities();
        // Schedule performance -My 
        public ActionResult Schedule(string id)
        {
            var khoabieu = db.BuoiHocs.Where(p => p.MKH == id).FirstOrDefault();
            return View(khoabieu);
        }

        public JsonResult GetEvents(string id)
        {
            var events = (from e in db.BuoiHocs.Where(p => p.MKH == id)
                          select new { e.MBH, e.Phong, e.Ngay, e.GioBatDau, e.GioKetThuc }).ToList();
            ;
            return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        [HttpPost]
        public JsonResult SaveEvent(BuoiHoc e)
        {
            var status = false;
            using (Sep2018Entities dc = new Sep2018Entities())
            {
                if (Convert.ToInt32(e.MBH) > 0)
                {
                    //Update the event
                    var v = dc.BuoiHocs.Where(a => a.MBH == e.MBH).FirstOrDefault();
                    if (v != null)
                    {
                        v.Phong = e.Phong;
                        v.Ngay = e.Ngay;
                        v.GioBatDau = e.GioBatDau;
                        v.GioKetThuc = e.GioKetThuc;
                        v.MKH = e.MKH;
                    }
                }
                else
                {
                    dc.BuoiHocs.Add(e);
                }
                dc.SaveChanges();
                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }
        public JsonResult ColorChanger(CauHinh e, int id)
        {
            var status = false;
            using (Sep2018Entities gun = new Sep2018Entities())
            {
                var v = gun.CauHinhs.Where(a => a.ID == id).FirstOrDefault();
                if (v != null)
                {
                    v.Attend = e.Attend;
                    v.Absent = e.Absent;
                    Session["Clr0"] = e.Absent;
                    Session["Clr1"] = e.Attend;
                }
                gun.SaveChanges();
                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }
        public ActionResult CreateSchedule(string id)
        {
            var schdl = db.GiangViens.Where(x => x.MGV == id).FirstOrDefault();
            return View(schdl);
        }
        [HttpPost]
        public JsonResult GatherScheduleData(CreateSchedule schdl)
        {
            var status = false;
           
            
             //var DateStart = (schdl.Dates.ToString().Split('-')[0]);
            //var changeDS = DateTime.Parse(DateStart.ToString().Split('/')[1] +"/"+ DateStart.ToString().Split('/')[0] +"/"+ DateStart.ToString().Split('/')[2]);
            //var DateEnd = schdl.Dates.ToString().Split('-')[1];
            //var changeDE = DateTime.Parse(DateEnd.ToString().Split('/')[1] + "/" + DateEnd.ToString().Split('/')[0] + "/" + DateEnd.ToString().Split('/')[2]);
            using (Sep2018Entities metal = new Sep2018Entities())
            {
                KhoaHoc khoahoc = metal.KhoaHocs.Single(p => p.MKH == schdl.CourseID);
                khoahoc.NgayBatDau = schdl.DateStart;
                khoahoc.NgayKetThuc = schdl.DateEnd;
                metal.SaveChanges();
                
                for (var i = schdl.DateStart; DateTime.Compare(i,schdl.DateEnd)<0; i=i.AddDays(1))
                {
                    int day = (int)i.DayOfWeek;
                    if (day == schdl.Days)
                    {
                        var B = new BuoiHoc();
                        B.MKH = schdl.CourseID;
                        B.GioBatDau = schdl.Start;
                        B.GioKetThuc = schdl.End;
                        B.Ngay = i;
                        B.Phong = schdl.Room;
                        metal.BuoiHocs.Add(B);
                        metal.SaveChanges();
                    }
                }
                
                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }
        [HttpGet]
        public ActionResult Settings(int id)
        {
            var thm = db.TaiKhoans.Where(x => x.ID == id).FirstOrDefault();
            return View(thm);
        }
        
        [HttpPost]
            public JsonResult EditAtd(int id)
        {
            var pistol = AtdChanger(id);
            return Json(new
            {
                status = pistol
            });
        }
        public int AtdChanger(int id)
        {
            var editor = db.DiemDanhs.Find(id);
            if (editor.TrangThai == 0)
            {
                editor.TrangThai = 1;
            }
            else if (editor.TrangThai == 1)
            {
                editor.TrangThai = 0;
            }
            db.SaveChanges();
            return (int)editor.TrangThai;
        }
        public ActionResult Attendance(string id, string MBH)    
        {
            int bh = Int32.Parse(MBH);
            var atd = db.DiemDanhs.Where(x => x.BuoiHoc.MKH.Equals(id) && x.MBH== bh).FirstOrDefault();
            if (atd != null)
            {
                return View(atd);
            }
            return Content("<script language='javascript' type='text/javascript'>alert('Không có dữ liệu');history.go(-1);</script>");
        }

        public ActionResult LoadData(string id, int e)
        {
            List<DiemDanh> _list = new List<DiemDanh>();
            try
            {
                _list = db.DiemDanhs.ToList();
                var result = from c in _list
                             where c.BuoiHoc.MKH.Equals(id) && c.BuoiHoc.MBH==e
                             select new[]
                             {
                                 Convert.ToString( c.ID),
                                 Convert.ToString( c.MSV ),
                                 Convert.ToString( c.SinhVien.Ho +" "+ c.SinhVien.Ten ),
                                 Convert.ToString( c.SinhVien.GioiTinh ),
                                 Convert.ToString( c.SinhVien.NgaySinh.ToString().Split(' ')[0] ),
                                 Convert.ToString( c.MBH ),
                                 Convert.ToString( c.Ngay ),
                                 Convert.ToString( c.Gio ),
                                 Convert.ToString( c.TrangThai ),
                             };
                return Json(new { aaData = result }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                //ErrorLogers.ErrorLog(ex);
                return Json(new
                {
                    aaData = new List<string[]> { }
                }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Course()
        {
            int idTK = Convert.ToInt32(Session["ID"]);
            string mgv = db.GiangViens.ToList().FirstOrDefault(p => p.IDTaiKhoan == idTK).MGV;
            //string idGV = db.TaiKhoans.ToList().FirstOrDefault(p => p.ID == idTK).TenTK;
            return View(db.KhoaHocs.Where(p => p.MGV == mgv).ToList());
        }
        public List<KhoaHoc> initData(string mgv)
        {
            List<KhoaHoc> kh = db.KhoaHocs.Where(x => x.MGV == mgv).ToList();
            return kh;
        }

        public PartialViewResult LoadCourse()
        {
            //System.Threading.Thread.Sleep(3000); //DEMO ONLY
            int idTK = Convert.ToInt32(Session["ID"]);
            string mgv = db.GiangViens.ToList().FirstOrDefault(p => p.IDTaiKhoan == idTK).MGV;
            API.GetAPI api = new API.GetAPI();
            api.getCourse(mgv);
            var listKH = db.KhoaHocs.Where(x => x.MGV == mgv).ToList();
            foreach (var item in listKH)
            {
                api.getMember(item.MKH);
            }
            List<KhoaHoc> kh = initData(mgv);
            return PartialView("_LoadCourse", kh);
        }

        //public ActionResult postAttendance()
        //{

        //}

        [HttpGet]
        public ActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordViewModel p)
        {
            if (ModelState.IsValid)
            {
                string message = "";
                if (p.OldPassword != null && p.NewPassword != null && p.ConfirmPassword != null)
                {
                    if (p.OldPassword == p.NewPassword)
                    {
                        message = "Mật khẩu mới không được giống mật khẩu cũ";
                        Session["CPMessage"] = message;
                        return View(p);
                    }
                    else
                    {
                        int id = Convert.ToInt32(Session["ID"]); // Get Session ID after login - HomeController for details
                        var user = db.TaiKhoans.FirstOrDefault(x => x.ID == id);
                        string oldpass = "";
                        byte[] buffer = Encoding.UTF8.GetBytes(p.OldPassword); // Mã hóa MD5
                        MD5CryptoServiceProvider md5 = new MD5CryptoServiceProvider();
                        buffer = md5.ComputeHash(buffer);
                        for (int i = 0; i < buffer.Length; i++)

SEP_FingerPrint/Views/Lecturer/Attendance.cshtml
@{
    ViewBag.Title = "Điểm danh";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //Layout = null;
    if (Session["ID"] != null)
    {
        if (Convert.ToInt32(Session["Role"]) == 2)
        {
            Response.Redirect("~/Admin/AddUser");
        }
    }
    else
    {
        Response.Redirect("~/Home/Login");
    }
}
@model SEP_FingerPrint.Models.DiemDanh
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Attendance</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.0/semantic.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.16/css/dataTables.semanticui.min.css" rel="stylesheet" />
    <style>
        tbody tr td {
            color: black;
        }
    </style>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.7.5/js/bootstrap-select.min.js"></script>*@
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.semanticui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.0/semantic.min.js"></script>
    <script src="~/CustomLib/Attendance/jquery.nice-select.js"></script>
    <link href="~/CustomLib/css/nice-select.css" rel="stylesheet" />
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <script>
        function showTable() {
            var time = $("#listTime").val().split(" ", 1);
            $("#example").DataTable({
                "processing": true,
                "serverSide": false,
                "pagingType": "full_numbers",
                "ordering": true,
                "info": true,
                "searching": true,
                "bFilter": false,
                //"scrollX": "100%",
                //"scrollY": ($(window).height() - 500),
                //"sScrollXInner": "100%",
                //"bScrollCollapse": true,
                //"sAjaxSource": 'http://localhost:49354/Lecturer/LoadData/@Model.BuoiHoc.MKH/'+time,
                "sAjaxSource": '@Url.Action("LoadData", "Lecturer")/@Model.BuoiHoc.MKH/@Model.BuoiHoc.MBH',
                //"fnServerParams": function (aoData) {
                //    aoData.push({ "name": "id", "value": "1" });
                //},
                "bDestroy": true,
                "bLengthChange": true,
                "bPaginate": true,
                "sEmptyTable": "Loading data from server",
                language: {
                    "search": "Tìm kiếm:",
                    "searchPlaceholder": "Nhập dữ liệu cần tìm",
                    "loadingRecords": "Đang tải dữ liệu...",
                    "processing": "Đang xử lý...",
                    "emptyTable": "Không tìm thấy dữ liệu",
                    "info": "Hiển thị _START_ đến _END_ trong tổng số _TOTAL_ dữ liệu",
                    "infoEmpty": "Hiển thị 0 trong tổng số 0 dữ liệu",
                    "infoFiltered": "(lọc từ tổng số _MAX_ dữ liệu)",
                    "lengthMenu": "Hiển thị _MENU_ dữ liệu",
                    "zeroRecords": "Không tìm thấy dữ liệu nào phù hợp",
                    "paginate": {
                        "first": "Đầu",
                        "last": "Cuối",
                        "next": "Tiếp theo",
                        "previous": "Trước đó"
                    },
                },
                "columns": [
                    //{
                    //    "render": function (data, type, row) {
                    //        return rows.count();
                    //    }
                    //},
                    { "render": function (data, type, row) { return row[1]; } },
                    { "render": function (data, type, row) { return (row[2]); } },
                    { "render": function (data, type, row) { return (row[3]); } },
                    { "render": function (data, type, row) { return (row[4]); } },
                    { "render": function (data, type, row) { return (row[8]); } },
                    {
                        "bSortable": false,
                        "targets": 0,
                        "render": function (data, type, row) {
                            if (row[8] == 0) {
                                //return '<div class="tg-list-item2"><input class="tgl2 tgl2-light" id="' + row[0] +'" type="checkbox" /><label class="tgl2-btn" data-tg-on="H" data-tg-off="V" for="'+ row[0] +'"></label></div>';
                                return '<button type="button" style="width: 95px; margin-top: 8px" class="btn-active btn btn-danger"'
                                                + 'aria-pressed="false" autocomplete="off" data-id="' + row[0] + '">Vắng</button>';
                            } else {
                                //return '<div class="tg-list-item2"><input class="tgl2 tgl2-light" id="'+ row[0] +'" type="checkbox" checked/><label class="tgl2-btn" data-tg-on="H" data-tg-off="V" for="'+ row[0] +'"></label></div>';
                                return '<button type="button" style="width: 95px; margin-top: 8px" class="btn-active btn btn-primary"'
                                                + 'aria-pressed="false" autocomplete="off" data-id="' + row[0] + '">Hiện diện</button>';
                            }
                        }
                    }
                ],
                rowCallback: function (row, data, index) {
                    if (data[8] == 0) {
                        $(row).find('td:eq(4)').text("").addClass('fa fa-close').css({ 'background': '@Session["Clr0"]', 'display': 'block', 'text-align': 'center' });
                    }
                    if (data[8] == 1) {
                        $(row).find('td:eq(4)').text("").addClass('fa fa-check').css({ 'background': '@Session["Clr1"]', 'display': 'block', 'text-align': 'center' });
                    }
                    if (data[3] == "True") {
                        $(row).find('td:eq(2)').text("").addClass('fa fa-male').css({ 'display': 'block', 'text-align': 'center'});
                    }
                    else {
                        $(row).find('td:eq(2)').text("").addClass('fa fa-female').css({ 'display': 'block', 'text-align': 'center' });
                    }

                    //
                    $(row).find('td:eq(0)').css({ 'text-align': 'center' });
                    $(row).find('td:eq(1)').css({ 'text-align': 'center' });
                    $(row).find('td:eq(3)').css({ 'text-align': 'center' });
                    $(row).find('td:eq(5)').css({ 'text-align': 'center' });
                    $("div.tg-list-item").show();
                    $(row).find('td:eq(5)').hide();
                    $(".tgl-btn").click(function () {
                        $(row).find('td:eq(5)').toggle();
                        $(row).find('td:eq(4)').toggle();
                        if ($('input.tgl').is(':checked')) {
                            location.reload();
                        }
                    });
                    //
                }
            });
            }
        $(document).ready(function () {
            $('select').niceSelect();
        });
        $(document).ready(function () {
            showTable();
            $("#listTime").change(function () {
                var time = $("#listTime").val().split(" ", 1);
                //var redirectURL = '@Url.Action("Attendance", "Lecturer")';
                window.location.href = '@Url.Action("Attendance", "Lecturer")?id=' + "@Model.MKH" + '&MBH=' +time;
                //showTable();
            });
        });
        //Edit attendance function
        setTimeout(function () {
            var editor = {
                init: function () {
                    editor.registerEvents();
                },
                registerEvents: function () {
                    $('.btn-active').on('click', function (e) {
                        e.preventDefault();
                        var btn = $(this);
                        var id = btn.data('id');
                        $.ajax({
                            url: "/Lecturer/EditAtd",
                            data: { id: id },
                            dataType: "json",
                            type: "POST",
                            success: function (response) {
                                console.log(response);
                                if (response.status == 0) {
                                    btn.text('Vắng').addClass('btn-danger');
                                    btn.text('Vắng').removeClass('btn-primary');
                                }
                                else {
                                    btn.text('Hiện diện').addClass('btn-primary');
                                    btn.text('Hiện diện').removeClass('btn-danger');
                                }
                            }
                        });
                    });
                }
            }
            editor.init();
        }, 3000);

    </script>
</head>

<div class="page-wrapper"  style="min-width: 700px">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">Điểm danh - buổi @Model.MBH</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Trang chủ</a></li>
                <li class="breadcrumb-item active">Điểm danh</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    <!-- Container fluid  -->
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="card">
            <div style="margin-left: 12px" class="row">
                <!-- /# column -->
                <div style="position:absolute; right: 30px; display: none" class="tg-list-item">
                    <input class="tgl tgl-skewed" id="cb3" type="checkbox" />
                    <label class="tgl-btn" data-tg-on="Hoàn thành" data-tg-off="Sửa điểm danh" for="cb3"></label>
                </div>
                <div id="example_length">
                    <select id="listTime">
                        <option>Chọn buổi học</option>
                        @{
                            SEP_FingerPrint.Models.Sep2018Entities db = new SEP_FingerPrint.Models.Sep2018Entities();
                            var listSel = db.BuoiHocs.ToList().Where(x=>x.MKH.Equals(@Model.MKH));
                            foreach (var item in listSel)
                            {
                                <option>@item.MBH - @item.Ngay.ToShortDateString()</option>
                            }
                        }
                    </select>
                </div>
                <div class="col-lg-12">
                    <hr />
                    <table id="example" class="table table-hover table-bordered dataTable" style="width:100%">
                        <thead>
                            <tr>
                                @*<th style="text-align: center">STT</th>*@
                                <th style="text-align: center">MSSV</th>
                                <th style="text-align: center">Họ tên</th>
                                <th style="text-align:center">Giới tính</th>
                                <th style="text-align: center">Ngày sinh</th>
                                <th id="done" style="text-align:center">
                                    Trạng thái
                                </th>
                                <th id="edit" style="text-align: center; display: none">Sửa</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
    <!-- End Container fluid  -->
</div>

SEP_FingerPrint/Views/Lecturer/ChangePassword.cshtml
@model SEP_FingerPrint.Models.ChangePasswordViewModel

@{
    ViewBag.Title = "Đổi mật khẩu";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["ID"] == null)
    {
        Response.Redirect("~/Home/Login");
    }
}
<head>
    <script src='~/CustomLib/Schedule/lib/jquery.min.js'></script>
</head>
<!--Body-->

<div class="page-wrapper">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">Đổi Mật Khẩu</h3>
        </div>
        @*<div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Trang chủ</a></li>
                <li class="breadcrumb-item active">Đổi Mật Khẩu</li>
            </ol>
        </div>*@
    </div>
    <!-- End Bread crumb -->

    <div class="container-fluid">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.OldPassword, htmlAttributes: new { @class = "control-label col-md-5" })
            
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OldPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OldPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "control-label col-md-5" })
                
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-5" })
               
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Change Password" class="btn btn-default" />
                </div>
            </div>
            <div class="form-group col-md-10">
                @{ string mess = Session["CPMessage"] as string;
                    if (mess != null)
                    {
                        <div style="color:black; font-size: 15px" class="alert alert-warning" role="alert">
                            <p>@mess</p>
                        </div>
                        Session.Remove("CPMessage");

                    }
                }
            </div>

        }

    </div>





</div>
<!--End Body-->

SEP_FingerPrint/Views/Lecturer/Course.cshtml
@model IEnumerable<SEP_FingerPrint.Models.KhoaHoc>

@{
    ViewBag.Title = "Khóa học";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["ID"] == null)
    {
        Response.Redirect("~/Home/Login");
    }
}
<script src="~/CustomLib/js/lib/jquery/jquery.min.js"></script>
<div class="page-wrapper">
    <!-- Bread crumb -->
    @*<div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h3 class="text-primary">Khóa học</h3>
            </div>
            <div class="col-md-7 align-self-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Khóa học</li>
                </ol>
            </div>
        </div>*@
    <!-- End Bread crumb -->
    <!-- Container fluid  -->
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <!-- /# column -->
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-title">
                        <h2 class="text-primary">Khóa học</h2>
                    </div>
                    <hr />
                    <div id="blokm">
                        <div id="blok1">
                            @*<a class="face-button" href="/Lecturer/CreateSchedule">
                                <div class="face-primary">
                                    <span class="icon fa fa-edit"></span>
                                </div>
                                <div class="face-secondary">
                                    Tạo lịch học
                                </div>
                            </a>*@
                        </div>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <div id="blok2">
                            <a>
                                @Ajax.ActionLink("Đồng bộ", "LoadCourse", "Lecturer", new AjaxOptions
                                {
                                    UpdateTargetId = "result",
                                    OnBegin = "",
                                    InsertionMode = InsertionMode.Replace,
                                    HttpMethod = "GET",
                                    LoadingElementId = "loadingElement2",
                                    OnSuccess = "",
                                    Confirm = "Bạn muốn đồng bộ danh sách khóa học hay không?"
                                }, new { @class = "btn btn-dark" })
                            </a>
                        </div>
                    </div>
                    <br />
                    <div class="card-body">
                        <div id="loadingElement2" style="display:none; color:#f60; text-align: center">
                            Đang tải dữ liệu...
                        </div>
                        <div id="result" class="table-responsive">
                            <table class="table table-hover ">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Tên môn học</th>
                                        <th>Mô tả</th>
                                        <th>Misc.</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.MKH</td>
                                            <td>@item.MonHoc.TenMonHoc</td>
                                            <td>@item.Note</td>
                                            <td>
                                                <a class="btn btn-primary btn-rounded" href="/Lecturer/FullAttendance/@item.MKH" id="@item.MKH">Điểm danh</a>|

                                                <a href="/Lecturer/Schedule/@item.MKH" role="button" class="btn btn-warning fa fa-info" name="@item.MKH"></a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
    <!-- End Container fluid  -->
</div>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

SEP_FingerPrint/Views/Lecturer/_LoadCourse.cshtml
@model List<SEP_FingerPrint.Models.KhoaHoc>
<table class="table table-hover ">
    <thead>
        <tr>
            <th>ID</th>
            <th>Tên môn học</th>
            <th>Mô tả</th>
            <th>Misc.</th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.MKH</td>
            <td>@item.MonHoc.TenMonHoc</td>
            <td>@item.Note</td>
            <td>
                <a href="/Lecturer/FullAttendance/@item.MKH" role="button" class="btn btn-primary btn-rounded">Điểm danh</a>
                |
                <a href="/Lecturer/Schedule/@item.MKH" role="button" class="btn btn-warning fa fa-info"></a>
            </td>
        </tr>
    }
        </tbody>
</table>